/**
 * Protocol v1 barrel (ADR-004).
 */
export {
  PROTOCOL_V1,
  PROTOCOL_ERROR_VERSION_MISMATCH,
  PROTOCOL_ERROR_MALFORMED,
  ProtocolVersionMismatchError,
  ProtocolDecodeError,
  assertProtocolVersion,
  validateMessage,
  encodeMessage,
  decodeMessage,
  decodeMessageValue,
  decodeMessageSafe,
  makeEnvelope,
  hello,
  welcome,
  playerState,
  chat,
  leave,
  ping,
  pong,
  errorMessage,
  type DecodeResult,
  type ProtocolEnvelope,
  type HelloPayload,
  type WelcomePayload,
  type PlayerStatePayload,
  type ChatPayload,
  type LeavePayload,
  type HeartbeatPayload,
  type ErrorPayload,
} from "./protocol-v1.js";
